version: '3.7'

networks:
  backend:
    name: backend

services:

  #==================GATEWAY================
  gateway-service:
    container_name: clipperms.gateway-service
    hostname: gateway-service
    image: ${GATEWAY_IMAGE}:${GATEWAY_IMAGE_TAG}

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s

    ports:
      - ${GATEWAY_PORT}:8762

    depends_on:
      - eureka-service

    networks:
      - backend

    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:${EUREKA_PORT}/eureka


  #==================EUREKA================
  eureka-service:
    container_name: clipperms.eureka-service
    hostname: eureka-service
    image: ${EUREKA_IMAGE}:${EUREKA_IMAGE_TAG}

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s

    ports:
      - ${EUREKA_PORT}:8761

    networks:
      - backend

    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:${EUREKA_PORT}/eureka


  #==================KEYCLOAK================
  keycloak-service:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: clipperms.keycloak-service
    hostname: keycloak-service
    environment:
      KC_DB: postgres
      KC_STORAGE: jpa
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin

      KC_TRANSACTION_XA_ENABLED: false

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO

      #      DEBUG: true  #set debug mode to debug custom keycloak providers while running keycloak in docker
      #      DEBUG_PORT: "*:8787"

    ports:
      - "8180:8180"
    #      - "8787:8787" # open debug port

    depends_on:
      - postgres-keycloak

    command:
      - start-dev --http-port=8180 #--log-level=DEBUG #start keycloak in dev mode with port 8180

    volumes:
      - .docker/keycloak_dev/json/export:/opt/keycloak/data #map the export folder of the linux machine to my windows folder

    networks:
      - backend



  #==================RABBITMQ================
  rabbitmq-service:
    container_name: clipperms.rabbitmq-service
    hostname: rabbitmq-service
    image: rabbitmq:management
    ports:
      - ${RABBIT_PORT}:${RABBIT_PORT}
      - "15672:15672"

    networks:
      - backend

  #==================trading================
  trading-module:
    container_name: clipperms.trading-module
    hostname: trading-module
    image: ${TRADING_IMAGE}:${TRADING_IMAGE_TAG}

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s

    #    expose:
    #      - ${TRADING_PORT} #expose trading port to machines inside docker network

    ports:
      - ${TRADING_PORT}:${TRADING_PORT} #expose trading port to host machine

    depends_on:
      - eureka-service
      - postgres-trad

    networks:
      - backend

    environment:
      spring.datasource.url: jdbc:postgresql://postgres-trad:5432/trading
      eureka.client.serviceUrl.defaultZone: http://eureka-service:${EUREKA_PORT}/eureka
      spring.rabbitmq.host: rabbitmq-service
      spring.rabbitmq.port: ${RABBIT_PORT}


  #==================collection================
  collection-module:
    container_name: clipperms.collection-module
    hostname: collection-module
    image: ${COLLECTION_IMAGE}:${COLLECTION_IMAGE_TAG}

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s

    #    expose:
    #      - ${COLLECTION_PORT} #expose collection port to machines inside docker network

    ports:
      - ${COLLECTION_PORT}:${COLLECTION_PORT} #expose collection port to host machine

    depends_on:
      - eureka-service
      - postgres-coll

    networks:
      - backend

    environment:
      spring.datasource.url: jdbc:postgresql://postgres-coll:5432/collection
      eureka.client.serviceUrl.defaultZone: http://eureka-service:${EUREKA_PORT}/eureka
      spring.rabbitmq.host: rabbitmq-service
      spring.rabbitmq.port: ${RABBIT_PORT}


  #========POSTGRES-COLL========#
  postgres-coll:
    image: postgres
    container_name: postgres-coll
    volumes:
      - .docker/postgres_data_dev/collection:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: collection
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    networks:
      - backend

  #========POSTGRES-TRAD========#
  postgres-trad:
    image: postgres
    container_name: postgres-trad
    volumes:
      - .docker/postgres_data_dev/trading:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5433:5432'
    networks:
      - backend

  #=======POSTGRES-KEYCLOAK=======#
  postgres-keycloak:
    image: postgres
    container_name: postgres-keycloak
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    volumes:
      - .docker/postgresql_data_keycloak:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend


#==================================#
#==========VOLUME-MAPPING==========#
#==================================#
volumes:
  postgres_data:
    driver: local