server:
  port: 8070

  # Context path of the application
  servlet:
    context-path: /trading/api


#Postgres database runs in docker
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trading
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: update
  application:
    name: Trading-module

org.slf4j.simpleLogger.defaultLogLevel: error

logging.level.org.springframework.jdbc.core: DEBUG

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    disable-swagger-default-url: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true


