server:
  port: 8070

  # Context path of the application
  servlet:
    context-path: /trading/api

#SPRING
spring:
  application:
    name: Trading-module

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=trading;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://clipper-ms.com:8180/realms/ClipperMS

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#SPRINGDOC OPENAPI
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    disable-swagger-default-url: true

#LOGGING
logging:
  level:
    org.springframework:
      amqp: DEBUG
      jdbc.core: DEBUG
org.slf4j.simpleLogger.defaultLogLevel: error
