server:
  port: 8070

  # Context path of the application
  servlet:
    context-path: /trading/api

#SPRING
spring:
  application:
    name: Trading-module

  datasource:
    url: jdbc:postgresql://localhost:5433/trading
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#SPRINGDOC OPENAPI
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    disable-swagger-default-url: true

#LOGGING
logging:
  level:
    org.springframework:
      amqp: DEBUG
      jdbc.core: DEBUG
org.slf4j.simpleLogger.defaultLogLevel: error
