#============SERVER============
server:
  # HTTP server port
  port: 8762

#============Spring============
spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - Accept
              - Content-Type
              - Authorization
              - Origin
              - Timezone
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
              - OPTIONS
      routes:
        #Trading
        - id: trading-service
          uri: lb://trading-module
          predicates:
            - Path=/trading/api/**

        #Collection
        - id: collection-service
          uri: lb://collection-module
          predicates:
            - Path=/collection/api/**

#============Eureka============
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


