@startuml
skinparam SequenceMessageAlignment center
actor User
participant "Client (FE)" as Client
participant "Collection Module" as Collection
participant "Keycloak" as Auth
participant "Database" as DB

User -> Client: Request to View Collection including JWT token
Client -> Collection: Fetch Collected clippers with User ID

activate Collection
Collection -> Auth: Validate JWT token
Auth -> Collection: Token Validated

Collection -> DB: Query for User's Collection of Clippers
DB -> Collection: Return Collection Data

Collection -> Client: Send Collection Data
deactivate Collection
Client -> User: Display Clippers Collection
@enduml
