server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

logging.level.com.netflix:
  eureka: OFF
  discovery: OFF
