#Postgres database runs in docker
spring:
  datasource:
    url: jdbc:h2:mem:collection
    username: collection
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate.format_sql: true
      ddl-auto: create-drop
      show-sql: true