#Postgres database runs in docker
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/test
    username: test
    password: test

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      ddl-auto: create-drop
      show-sql: true