server:
  port: 8071

# Context path of the application
  servlet:
    context-path: /collection/api

#SPRING
spring:
  application:
    name: Collection-module

  datasource:
    url: jdbc:postgresql://localhost:5432/collection
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
        format_sql: true
        ddl-auto: update

#SPRINGDOC OPENAPI
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    disable-swagger-default-url: true

#LOGGING
org.slf4j.simpleLogger.defaultLogLevel: error
logging.level.org.springframework.jdbc.core: DEBUG

