server:
  port: 8071

# Context path of the application
  servlet:
    context-path: /collection/api

#SPRING
spring:
  application:
    name: Collection-module

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=collection;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: admin
    password: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    properties:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://clipper-ms.com:8180/realms/ClipperMS/protocol/openid-connect/certs
          issuer-uri: http://clipper-ms.com:8180/realms/ClipperMS


#SPRINGDOC OPENAPI
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    disable-swagger-default-url: true

#LOGGING
org.slf4j.simpleLogger.defaultLogLevel: error
logging.level.org.springframework.jdbc.core: DEBUG

