apiVersion: v1
kind: Secret
metadata:
  name: fe-secrets
type: Opaque
data:
  REACT_APP_API_BASE_URL: aHR0cDovL2NsaXBwZXItbXMuY29t
  REACT_APP_KEYCLOAK_URL: aHR0cDovLzIwLjc5LjEyOC4yNDM6ODE4MA==
  REACT_APP_KEYCLOAK_REALM: Q2xpcHBlck1T
  REACT_APP_KEYCLOAK_CLIENT_ID: Y2xpcHBlci1jbGllbnQ=
  REACT_APP_KEYCLOAK_LOGIN_URL: aHR0cDovL2NsaXBwZXItbXMuY29tLw==
  REACT_APP_KEYCLOAK_LOGOUT_URL: aHR0cDovL2NsaXBwZXItbXMuY29tLw==
