apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak-service
    spec:
      containers:
        - args:
            - start-dev --http-port=8180
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_PASSWORD
              value: admin
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres-keycloak:5432/keycloak
            - name: KC_DB_USERNAME
              value: admin
            - name: KC_STORAGE
              value: jpa
            - name: KC_TRANSACTION_XA_ENABLED
              value: "false"
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_LOGLEVEL
              value: INFO
          image: quay.io/keycloak/keycloak:22.0.1
          name: keycloak-service
          ports:
            - containerPort: 8180
          resources: {}
          volumeMounts:
            - mountPath: /opt/keycloak/data
              name: keycloak-service-claim0
      hostname: keycloak-service
      restartPolicy: Always
      volumes:
        - name: keycloak-service-claim0
          persistentVolumeClaim:
            claimName: keycloak-service-claim0
