apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-module
  template:
    metadata:
      labels:
        app: trading-module
    spec:
      containers:
        - name: trading-module
          image: mhormes/trading-module:v0.2
          imagePullPolicy: Always
          env:
            - name: spring.datasource.url
              value: jdbc:sqlserver://clipperms.database.windows.net:1433;database=trading;user=clipper-admin@clipperms;password={password};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
            - name: spring.rabbitmq.host
              value: rabbitmq-service
            - name: spring.rabbitmq.port
              value: "5672"
          ports:
            - containerPort: 8070
          resources: {}
